name: Weather Alert CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
        python-version: ['3.10', '3.11', '3.12', '3.13']
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies and setup environment
      run: |
        pip install uv
        uv venv
        uv sync --dev
      shell: bash
    
    - name: Run Ruff
      run: |
        uv run ruff check .
        uv run ruff format --check .
      shell: bash
    
    - name: Run pytest with coverage
      run: |
        uv pip install pytest-cov
        uv run pytest --cov=weather_alert tests/ --cov-report=xml
      shell: bash
    
    # - name: Upload coverage
    #   uses: codecov/codecov-action@v4
    #   env:
    #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    #   if: matrix.os == 'ubuntu-latest'